# Generated by Django 4.1.3 on 2023-01-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_orderitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_history', to='orders.order')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_history', to='orders.order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='orders.order')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_product_history', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='orders.orderitem')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_quantity_history', to='orders.orderitem')),
            ],
        ),
    ]
