# Generated by Django 4.1.3 on 2023-01-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryOrder',
        ),
    ]
