# Generated by Django 4.1.3 on 2022-12-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact_delete_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
