# Generated by Django 4.1.3 on 2023-01-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order']},
        ),
    ]
