# Generated by Django 4.1.3 on 2023-01-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
